version: "3.8"

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: proyectofinal-otel-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"

  app:
    build: .
    container_name: proyectofinal-app
    ports:
      - "80:5000"
    volumes:
      - ./db:/app/db
    depends_on:
      - otel-collector

  prometheus:
    image: prom/prometheus:latest
    container_name: proyectofinal-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - otel-collector

  grafana:
    image: grafana/grafana:latest
    container_name: proyectofinal-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana   # <— aquí guardamos la base de datos de Grafana

# Definición de volúmenes persistentes
volumes:
  grafana_data:
