receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  debug:
    verbosity: normal
  prometheus:
    endpoint: "0.0.0.0:9464"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [debug]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheus]
