global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']

  - job_name: 'flask-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:5000']
